<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
    <ProjectReference Include="..\TeleSelfCloud.Core\TeleSelfCloud.Core.csproj" />
    <ProjectReference Include="..\TeleSelfCloud.Infrastructure\TeleSelfCloud.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\THIRD_PARTY_NOTICES.md" Link="THIRD-PARTY-NOTICES.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\docs\INSTALL_WINDOWS.md" Link="INSTALL_WINDOWS.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\Apache-2.0.txt" Link="licenses\Apache-2.0.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\BSL-1.0.txt" Link="licenses\BSL-1.0.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\DOTNET-THIRD-PARTY-NOTICES.txt" Link="licenses\DOTNET-THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\MIT.txt" Link="licenses\MIT.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\SQLITE3MC-MIT.txt" Link="licenses\SQLITE3MC-MIT.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\WINDOWS-DESKTOP-RUNTIME-LICENSE.txt" Link="licenses\WINDOWS-DESKTOP-RUNTIME-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\..\licenses\Zlib.txt" Link="licenses\Zlib.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  

  <PropertyGroup>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
